### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by darrenoh** [cosmicdreams/drupal-storybook#2]
Following the instructions in the README, I get an error.
```
% ddev yarn storybook
yarn run v1.22.19
warning package.json: No license field
$ start-storybook -p 6006
info @storybook/server v6.5.16
info 
info => Loading presets
info => Loading custom manager config
info Addon-docs: using MDX1
info => Using implicit CSS loaders
info => Using default Webpack5 setup
info => Loading custom manager config
<i> [webpack-dev-middleware] wait until bundle finished
10% building 0/1 entries 0/0 dependencies 0/0 modules
info => Using cached manager
99% done plugins webpack-hot-middlewarewebpack built preview f900e648a2c21f9e2da7 in 4521ms
ModuleNotFoundError: Module not found: Error: Can't resolve '@storybook/preview-api' in '/var/www/html/node_modules/@lullabot/storybook-drupal-addon/dist'
    at /var/www/html/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/Compilation.js:2022:28
    at /var/www/html/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModuleFactory.js:817:13
    at eval (eval at create (/var/www/html/node_modules/@storybook/builder-webpack5/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /var/www/html/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/var/www/html/node_modules/@storybook/builder-webpack5/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /var/www/html/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModuleFactory.js:448:22
    at /var/www/html/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModuleFactory.js:118:11
    at /var/www/html/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModuleFactory.js:689:25
    at /var/www/html/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModuleFactory.js:893:8
    at /var/www/html/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModuleFactory.js:1013:5
resolve '@storybook/preview-api' in '/var/www/html/node_modules/@lullabot/storybook-drupal-addon/dist'
  Parsed request is a module
  using description file: /var/www/html/node_modules/@lullabot/storybook-drupal-addon/package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /var/www/html/node_modules/@lullabot/storybook-drupal-addon/dist/node_modules doesn't exist or is not a directory
      /var/www/html/node_modules/@lullabot/storybook-drupal-addon/node_modules doesn't exist or is not a directory
      /var/www/html/node_modules/@lullabot/node_modules doesn't exist or is not a directory
      /var/www/html/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /var/www/html/node_modules
        single file module
          using description file: /var/www/html/package.json (relative path: ./node_modules/@storybook/preview-api)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /var/www/html/node_modules/@storybook/preview-api doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /var/www/html/node_modules/@storybook/preview-api.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /var/www/html/node_modules/@storybook/preview-api.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /var/www/html/node_modules/@storybook/preview-api.jsx doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /var/www/html/node_modules/@storybook/preview-api.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /var/www/html/node_modules/@storybook/preview-api.tsx doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /var/www/html/node_modules/@storybook/preview-api.json doesn't exist
            .cjs
              Field 'browser' doesn't contain a valid alias configuration
              /var/www/html/node_modules/@storybook/preview-api.cjs doesn't exist
        /var/www/html/node_modules/@storybook/preview-api doesn't exist
      /var/www/node_modules doesn't exist or is not a directory
      /var/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

info => Loading presets
99% done plugins webpack-hot-middlewarewebpack built preview 6610890dd429dd74f4b3 in 1231ms
```

**Comment by cosmicdreams** [comment]
@darrenoh I thought I was doing a good thing by not committing the yarn.lock file but now I see that it leads to problems like this.  I did a yarn install on my local and it had a bunch changes that didn't actually make it into source control.  

Please pull the latest and try again.

**Comment by cosmicdreams** [comment]
It's been a while since this issue was created @darrenoh I think I might have solved your issue along the way.  Can you retest?
